### ISSUE TITLE
咋更新呀？

### ISSUE THREAD

**Issue by xccoco** [D-Sketon/hexo-theme-reimu#10]
如题，不想在每次更新博客时看到 warning，但是图标颜色等魔改的比较多，不是很能重新配。所以有更新版本的方法吗？

**Comment by D-Sketon** [comment]
fork一份我的仓库然后在这个上面改，如果有更新的话和我的主分支merge一下就行

**Comment by D-Sketon** [comment]
Warning要不你手动把相关代码删了吧😂

**Comment by xccoco** [comment]
哦哦谢谢大佬！
