### ISSUE TITLE
如何启用live-2d看板娘？

### ISSUE THREAD

**Issue by wh210758** [D-Sketon/hexo-theme-reimu#12]

**Comment by MliKiowa** [comment]
@D-Sketon 
我觉得实现很简单
我从halo的一个插件删除了一些东西 让他脱离halo环境 同时去掉了aichat部分
原插件 https://github.com/MliKiowa/plugin-live2d
我稍微删改了下 https://github.com/MliKiowa/plugin-live2d
我放了个test.html 不过问题是
这个主题配上这个感觉不是特别好看 有必要添加吗

**Comment by D-Sketon** [comment]
> @D-Sketon 我觉得实现很简单 我从halo的一个插件删除了一些东西 让他脱离halo环境 同时去掉了aichat部分 原插件 https://github.com/LIlGG/plugin-live2d 我稍微删改了下 https://github.com/MliKiowa/plugin-live2d 我放了个test.html 不过问题是 这个主题配上这个感觉不是特别好看 有必要添加吗

![image](https://github.com/D-Sketon/hexo-theme-reimu/assets/49871906/24b8b778-ede1-4649-8ecb-220d14a3f0ca)

感觉还行吧哈哈

**Comment by MliKiowa** [comment]
> > @D-Sketon 我觉得实现很简单 我从halo的一个插件删除了一些东西 让他脱离halo环境 同时去掉了aichat部分 原插件 https://github.com/LIlGG/plugin-live2d 我稍微删改了下 https://github.com/MliKiowa/plugin-live2d 我放了个test.html 不过问题是 这个主题配上这个感觉不是特别好看 有必要添加吗
> 
> ![image](https://private-user-images.githubusercontent.com/49871906/294869079-24b8b778-ede1-4649-8ecb-220d14a3f0ca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3MDk5NzIsIm5iZiI6MTcwNDcwOTY3MiwicGF0aCI6Ii80OTg3MTkwNi8yOTQ4NjkwNzktMjRiOGI3NzgtZWRlMS00NjQ5LThlY2ItMjIwZDE0YTNmMGNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDEwMjc1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZiN2JkOTUzNDQ2NzE4MjdjMzEyODQ0YWI1MGVmZmRkNmE4YzM4NjE1OTFmOThkMjhjZGNiYzM3NmEzMmQ4OWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nOfFsLGO44dcIn5KGIqWc0XZypWnP6ysYoaVrdOJH_s)
> 
> 感觉还行吧哈哈

那就加吧 大家都有的 我们也要有

**Comment by D-Sketon** [comment]
closed by d1c96d52b956717567dd6bbe74ebf2125ae7fbc2
