### ISSUE TITLE
生成阶段错误 提示TypeError

### ISSUE THREAD

**Issue by MliKiowa** [D-Sketon/hexo-theme-reimu#18]
![image](https://github.com/D-Sketon/hexo-theme-reimu/assets/61873808/e61b2621-1481-4a60-a232-0166c83f8bef)

hexo 7.0.0 提示错误如图 我没有开发过hexo主题 我不知道怎么处理问题
顺便一提 关于live2d的那个js我之后整个包吧 之后用unpkg jsdelivr经常抽风

**Comment by D-Sketon** [comment]
fix in a88d3ea344177f2621f8240b1b3127c38736f653
