### ISSUE TITLE
md文件中直接嵌入html内容

### ISSUE THREAD

**Issue by wh210758** [D-Sketon/hexo-theme-reimu#20]
请问如果想在md文件中直接嵌入html内容应该如何做？

**Comment by D-Sketon** [comment]
可以卸载 `hexo-renderer-marked` 转而使用诸如 `hexo-renderer-markdown-it` 或者 `hexo-renderer-markdown-it-plus` 这类渲染器，这些渲染器支持直接嵌入html并能在_config.yml中进行配置
