### ISSUE TITLE
文章封面显示特定内容

### ISSUE THREAD

**Issue by wh210758** [D-Sketon/hexo-theme-reimu#21]
我想要在主页文章封面上显示自定义的文章概括，就像演示网站一样，使用description标签貌似不行，请问改如何解决呢？
![image](https://github.com/D-Sketon/hexo-theme-reimu/assets/137261065/2073154e-e301-4547-9f20-05631b8c706f)

**Comment by D-Sketon** [comment]
使用excerpt字段
