### ISSUE TITLE
使用hexo-encrypt解密后右侧目录（侧边栏）为空

### ISSUE THREAD

**Issue by chengyiqiu1121** [D-Sketon/hexo-theme-reimu#24]
使用了hexo插件“hexo-blog-encrypt”来加密文章，在输入正确的密码后，文章右侧的目录内容为空。
没有加密的文章：
<img width="1222" alt="截屏2024-04-27 08 54 47" src="https://github.com/D-Sketon/hexo-theme-reimu/assets/147218976/bb021400-718c-4fb8-a442-2388dd82ea79">
加密过的文章，在输入正确密码之后：
<img width="1220" alt="截屏2024-04-27 08 54 33" src="https://github.com/D-Sketon/hexo-theme-reimu/assets/147218976/f7280bf5-5667-4394-bca1-6171f0611504">

**Comment by D-Sketon** [comment]
hexo-encrypt 没有提供对应方式控制TOC，且已无人维护，无法适配
hexo-blog-encrypt 将在v0.1.2中进行适配
