### ISSUE TITLE
hexo-blog-decrypt 加密后，代码框没有高亮

### ISSUE THREAD

**Issue by chengyiqiu1121** [D-Sketon/hexo-theme-reimu#25]
正常的文章的代码框：
<img width="1202" alt="image" src="https://github.com/D-Sketon/hexo-theme-reimu/assets/147218976/4266855d-22f7-4fb3-9dbe-22da3750f60c">

加密后的文章的代码框：
<img width="1189" alt="image" src="https://github.com/D-Sketon/hexo-theme-reimu/assets/147218976/0ffdaba7-cdff-425c-8c43-5fa6e8f10b15">

输入密码后，第一次加载不会加载高亮代码框。然后后面一段时间内再次打开blog，不需要输入密码，应该是cookie，高亮代码框就能正常显示了。

**Comment by D-Sketon** [comment]
这个插件真的折磨🌚
应该是一些代码没有成功运行，我到时候看看

**Comment by chengyiqiu1121** [comment]
大佬辛苦了，给大佬递茶
![9c84c259622b2f9ff37d39a97b9292ea](https://github.com/D-Sketon/hexo-theme-reimu/assets/147218976/98570db5-f7dc-4247-8c74-cc9bc2170b50)

**Comment by D-Sketon** [comment]
我在 https://github.com/D-Sketon/hexo-theme-reimu/commit/bdd950dadcd4bf53daf4273487ef955c8153de94 里修复了这个bug。你可以通过 git clone 的方式更新主题看看还有没有hexo-blog-decrypt相关的bug，如果没有的话我再发个新版本。

**Comment by chengyiqiu1121** [comment]
> 我在 [bdd950d](https://github.com/D-Sketon/hexo-theme-reimu/commit/bdd950dadcd4bf53daf4273487ef955c8153de94) 里修复了这个bug。你可以通过 git clone 的方式更新主题看看还有没有hexo-blog-decrypt相关的bug，如果没有的话我再发个新版本。

可以了佬，现在输入密码后，目录和代码框都能够正常加载了。
