### ISSUE TITLE
v0.2.1 "avatar.webp"无法加载到页面

### ISSUE THREAD

**Issue by ghriver** [D-Sketon/hexo-theme-reimu#35]
你好，我在尝试放入avatar.webp文件时发现在主题配置文件中提供的路径不存在，请问该怎么解决呢（作者头像处显示的也只有作者名称）
Infomations：
Hexo 7
reimu v0.2.1
language zh-CN
Node.js 18

**Comment by D-Sketon** [comment]
参考 https://github.com/D-Sketon/hexo-theme-reimu/tree/main/_example/_data/avatar 的结构
`avatar.webp` 放在 `source\_data\avatar` 下

**Comment by ghriver** [comment]
好的谢谢，have a nice day!

**Comment by ghriver** [comment]
> 参考 https://github.com/D-Sketon/hexo-theme-reimu/tree/main/_example/_data/avatar 的结构
> 
> `avatar.webp` 放在 `source\_data\avatar` 下，`_data` 文件夹需要自己新建

好的，谢谢，have a nice day!

**Comment by ghriver** [comment]
@D-Sketon 好的，谢谢，have a nice day!
