### ISSUE TITLE
请教一些事情

### ISSUE THREAD

**Issue by Huayuluoshi** [D-Sketon/hexo-theme-reimu#37]
开发者你好，很抱歉占用你的时间，但是我遇到了一些麻烦：
1.我找不到_source文件夹，hexo生成的和git clone下来的都不带_。hexo版本是7.3.0
2.是不是需要额外用npm安装一些依赖项？我直接应用本主题的结果是这样的：
![17232628955592499134534656218254](https://github.com/user-attachments/assets/faae0c2b-983b-461c-90e0-189e8dc70a22)
3.这点我不确定该不该提，因为对我这种第一次应用如此复杂的主题，请问是否有更为详尽的文档或者视频可以参考？如果有的话请问可以指个路吗？

万分感谢！

**Comment by D-Sketon** [comment]
1. 我readme写错了，应该是source
2. 基础使用的话是不需要额外的依赖项，你可以看看hexo s 和f12控制台有没有报错信息，如果有的话可以发出来协助排查问题
3. 这个现在确实没有= =

**Comment by Huayuluoshi** [comment]
> 1. 我readme写错了，应该是source
> 
>     2. 基础使用的话是不需要额外的依赖项，你可以看看hexo s 和f12控制台有没有报错信息，如果有的话可以发出来协助排查问题
> 
>     3. 这个现在确实没有= =

谢谢回复，我再折腾折腾看

**Comment by Huayuluoshi** [comment]
报错：`Uncaught ReferenceError: jQuery is not defined
    <anonymous> http://isfafa.top/js/script.js:138
[script.js:138:4](http://isfafa.top/js/script.js)
    <anonymous> http://isfafa.top/js/script.js:138
Uncaught ReferenceError: _$$ is not defined
    <anonymous> http://isfafa.top/js/pjax_script.js:45
[pjax_script.js:45:1](http://isfafa.top/js/pjax_script.js)
Uncaught ReferenceError: _$$ is not defined
    <anonymous> http://isfafa.top/js/insert_highlight.js:2
    <anonymous> http://isfafa.top/js/insert_highlight.js:93
[insert_highlight.js:2:3](http://isfafa.top/js/insert_highlight.js)
由于非 HTTPS Cookie 无法设置“secure”属性，已拒绝 Cookie “busuanziId”。 [busuanzi](http://busuanzi.ibruce.info/busuanzi?jsonpCallback=BusuanziCallback_16669083759)
由于非 HTTPS Cookie 无法设置“secure”属性，已拒绝 Cookie “busuanziId”。`
警告：`即使其 MIME 类型（“application/json”）不是有效的 JavaScript MIME 类型，仍已加载来自“http://busuanzi.ibruce.info/busuanzi?jsonpCallback=BusuanziCallback_16669083759”的脚本。
[isfafa.top](http://isfafa.top/)
通过 link preload 预加载的资源“http://at.alicdn.com/t/c/font_4552607_tq6stt6tcg.woff2”并未在加载后几秒内使用。请确保 preload 标签的所有属性均设置无误。 [isfafa.top](http://isfafa.top/)`

**Comment by Huayuluoshi** [comment]
更新：疑似未启用ssl导致，正在测试中。

**Comment by D-Sketon** [comment]
有点奇怪，现在的reimu代码里应该是没有jQuery的

**Comment by Huayuluoshi** [comment]
更新2：开启ssl证书后访问正常
![Uploading 17232685597147614359382657821501.jpg…]()
