### ISSUE TITLE
The problem of the url name

### ISSUE THREAD

**Issue by luliqwerty** [D-Sketon/hexo-theme-reimu#45]
In my post url 
I find the the  url has some problem.  I's like 2024/09/01/2024-09-02-try-of-Dvorak/
The url did't corresponding to the file name. Every post had this problem. I tried to delete previous post and reload them but there is no use.
I'm not good at that, please help me.

**Comment by D-Sketon** [comment]
what's your permalink in _config.yml?

**Comment by luliqwerty** [comment]
permalink: :year/:month/:day/:title/
I tried to modify that previously, but it doesn't work.
When I use hexo g && hexo s won't lead to such a result, but github pages will.

**Comment by D-Sketon** [comment]
if your filename is 2024-09-02-try-of-Dvorak.md, then I don't feel there's anything wrong with it.

**Comment by luliqwerty** [comment]
2024/09/01/
9-1
2024-09-02-try-of-Dvorak/
9-2
the parameter ‘day’ of url has problem.

**Comment by D-Sketon** [comment]
The problem is probably the same as https://github.com/hexojs/hexo/issues/2063. it's a time zone issue.
You could try writing the date in front-matter more completely.

**Comment by luliqwerty** [comment]
The problem have solved, thank you very much.
