### ISSUE TITLE
firefox灵梦光标显示问题

### ISSUE THREAD

**Issue by TonyXie30** [D-Sketon/hexo-theme-reimu#47]
在firefox打开网站，鼠标光标显示为黑白色
![mouse Mozilla Firefox](https://github.com/user-attachments/assets/cbeb8bd5-13e8-4046-a245-c5feecba4dde)
然而在chrome打开时，鼠标光标显示为彩色
![mouse Chrome](https://github.com/user-attachments/assets/4f2543d6-0c0d-443e-abb1-5e1f8610d8c2)
我使用的firefox版本为130.0，在win10/11上使用均有上述问题

**Comment by D-Sketon** [comment]
替换为了png
