### ISSUE TITLE
安装教程错误

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [D-Sketon/hexo-theme-reimu#48]
我依据Readme中的示例配置文件进行修改时出现了错误

```
# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: reimu
```
Hexo一直提示No layout :index.html
最终我发现主题应配置为
`theme: hexo-theme-reimu`
因为使用git clone https://github.com/D-Sketon/hexo-theme-reimu.git 命令时创建的文件夹名称为hexo-theme-reimu.
这可能是因为作者修改项目名称时没有修改Readme导致的
这个sb问题困扰了我大半天

**Comment by D-Sketon** [comment]
> 或直接克隆本仓库至 /themes 文件夹下并重命名为 reimu

readme有提到需要重命名文件夹

**Comment by Nippaku-Zanmu** [comment]
> > 或直接克隆本仓库至 /themes 文件夹下并重命名为 reimu
> 
> readme有提到需要重命名文件夹

没看到 抱歉给你带来麻烦了
