### ISSUE TITLE
关于和友链界面乱码问题 

### ISSUE THREAD

**Issue by Nippaku-Zanmu** [D-Sketon/hexo-theme-reimu#49]
<img width="827" alt="brave_9lxwef9xbC" src="https://github.com/user-attachments/assets/1f833efd-e125-41fc-9d3a-df9a0df2e2d0">

<img width="630" alt="brave_iBFyOmCeN2" src="https://github.com/user-attachments/assets/6b9a56af-3d43-4ca8-a59a-db9deab9048c">

<img width="528" alt="brave_Qp8viIJtcS" src="https://github.com/user-attachments/assets/367860be-4de4-4efd-8e0a-c5e95215e57e">

<img width="836" alt="brave_RLp3uXUN52" src="https://github.com/user-attachments/assets/bc1f9932-3aba-49cd-a2a6-d61d85c5a160">
如图所示 主页是正常的
系统版本 Windows11

**Comment by Nippaku-Zanmu** [comment]
hexo version

hexo-cli: 4.3.2
os: win32 10.0.22000 undefined
node: 20.17.0
acorn: 8.11.3
ada: 2.9.0
ares: 1.32.3
base64: 0.5.2
brotli: 1.1.0
cjs_module_lexer: 1.2.2
cldr: 45.0
icu: 75.1
llhttp: 8.1.2
modules: 115
napi: 9
nghttp2: 1.61.0
nghttp3: 0.7.0
ngtcp2: 1.1.0
openssl: 3.0.13+quic
simdutf: 5.3.0
tz: 2024a
undici: 6.19.2
unicode: 15.1
uv: 1.46.0
uvwasi: 0.0.21
v8: 11.3.244.8-node.23
zlib: 1.3.0.1-motley-209717d

**Comment by D-Sketon** [comment]
关于乱码：将language改成zh-CN并检查友链的md文件的编码是否为utf-8
渲染异常：我无法复现，需要了解source下的文件结构和_config.yml中的配置信息

**Comment by Nippaku-Zanmu** [comment]
> 关于乱码：将language改成zh-CN并检查友链的md文件的编码是否为utf-8 渲染异常：我无法复现，需要了解source下的文件结构和_config.yml中的配置信息

我的配置文件中的语言选项均为zh-CN 并且配置是使用的example里面的 编码都是utf-8 但是仍然是乱码
感谢您的帮助

**Comment by Nippaku-Zanmu** [comment]
> > 关于乱码：将language改成zh-CN并检查友链的md文件的编码是否为utf-8 渲染异常：我无法复现，需要了解source下的文件结构和_config.yml中的配置信息
> 
> 我的配置文件中的语言选项均为zh-CN 并且配置是使用的example里面的 编码都是utf-8 但是仍然是乱码 感谢您的帮助
<img width="563" alt="explorer_7yYMzUbVNK" src="https://github.com/user-attachments/assets/63b40d9f-688e-4158-9654-857b7a7d988f">

**Comment by Nippaku-Zanmu** [comment]
[source.zip](https://github.com/user-attachments/files/17076004/source.zip)
[_conf
[_config.zip](https://github.com/user-attachments/files/17076011/_config.zip)
igtheme.zip](https://github.com/user-attachments/files/17076008/_configtheme.zip)

**Comment by D-Sketon** [comment]
我使用你给的文件测试了一下，仍然无法复现😓
能否提供一下package.json

**Comment by Nippaku-Zanmu** [comment]
[package.zip](https://github.com/user-attachments/files/17076334/package.zip)


> 我使用你给的文件测试了一下，仍然无法复现😓 能否提供一下package.json

十分感谢

**Comment by D-Sketon** [comment]
啊这，我还是不能复现，要不你试试我的工程，安装依赖后直接hexo s试试
[reimu-demo.zip](https://github.com/user-attachments/files/17077265/reimu-demo.zip)

**Comment by Nippaku-Zanmu** [comment]
> 啊这，我还是不能复现，要不你试试我的工程，安装依赖后直接hexo s试试 [reimu-demo.zip](https://github.com/user-attachments/files/17077265/reimu-demo.zip)

十分感谢 可以正常运行了
