### ISSUE TITLE
请问作者大大可以发布个hugo版本的吗?

### ISSUE THREAD

**Issue by Huayuluoshi** [D-Sketon/hexo-theme-reimu#53]
如题，因为我的博客服务器使用宝塔面板，npm管理有点诡异（比如头像什么的会被覆盖？）而且宝塔面板的nodejs管理器升级npm版本会相当于重装npm
所以我换了hugo，但是感觉这款主题很不错，还想用，奈何自己没实力qaq
所以请问作者大大有计划做hugo版本的吗?
**考虑付费，如果可以的话可以提下价格，感谢**

**Comment by D-Sketon** [comment]
hugo版近期会考虑制作

**Comment by Huayuluoshi** [comment]
> hugo版近期会考虑制作

感谢！

**Comment by D-Sketon** [comment]
目前实现了一个基础的Hugo主题 https://github.com/D-Sketon/hugo-theme-reimu/

**Comment by Huayuluoshi** [comment]
已Starred,已捐赠（有点少，但是学牲实在那不出多的qaq，希望大大别嫌弃）
