### ISSUE TITLE
评论区会错误显示在home和archives界面，在about和friend界面是正常的

### ISSUE THREAD

**Issue by qllokirin** [D-Sketon/hexo-theme-reimu#55]
我配置了giscus为true，但然后评论区会错误显示在home和archives界面，在about和friend界面是正常的
![image](https://github.com/user-attachments/assets/9f73d196-f496-486f-8830-891b3169dcdc)
查看我的[博客链接](https://qllokirin.github.io/)

以及想问问home archives about friend怎么设置为中文，我在本地hexo s显示的是英文，用github page推上去又变成日语了，好神奇，请问一下应该怎么改呢

**Comment by D-Sketon** [comment]
_config.yml中
```yml
language: zh-CN
```
应该可以解决语言问题

giscus 问题马上修复

**Comment by D-Sketon** [comment]
v0.3.3理论上修复了该问题，如仍然有问题请重新打开该issue

**Comment by qllokirin** [comment]
感谢佬的极速修复与解答，已经ok了，这主题真的很棒！
