### ISSUE TITLE
評論區未顯示

### ISSUE THREAD

**Issue by magicboy0409** [D-Sketon/hexo-theme-reimu#56]
我true後，也在Waline跟Vercel部屬完了，也填上網址了(我圖片上沒填，但部屬時有)，為甚麼評論區還是沒有出現在我的blog？
以及我的favicon.ico在放到了images/後，新的圖案會變成原本的圖案，但是打開來後是新的，可是網站的icon依然是舊的
<img width="331" alt="image" src="https://github.com/user-attachments/assets/0492924f-67cb-4bcf-a0e0-edfaaa44de1d">

**Comment by D-Sketon** [comment]
1. 如果你的博客有`_config.reimu.yml`，请优先在此编辑配置
2. 尝试先运行`hexo cl`清除缓存后再重新生成网站

**Comment by magicboy0409** [comment]
1. 我的reimu裡的config.yml沒有設置comment，我需要手動加入他嗎？
![image](https://github.com/user-attachments/assets/b0caff17-c38d-40a7-adfb-b454feeb327b)
2. 我有確實的先hexo cl再hexo g，儘管我把images裡的favicon.ico檔案移走，依然會生成favicon.ico，我將我要的icon移回來，再次生成，依然是原本的
![image](https://github.com/user-attachments/assets/bee34aca-d2b2-4e4f-ad8f-82379b573563)

順帶一提，資料夾裡的預覽圖是原本的
<img width="1262" alt="image" src="https://github.com/user-attachments/assets/a7b89aee-8469-4f5c-b56f-f844dd164e5e">

**Comment by D-Sketon** [comment]
咦，你是npm安装的主题还是git clone安装的主题？为什么reimu文件夹不在themes文件夹里

**Comment by magicboy0409** [comment]
我用clone 的，我一開始是放在theme裡面，但hexo s時正常，hexo d就會跑版，放在最外面才正常，我也覺得怪怪的，裡面的hexo.theme.walin.enable指的是類還是這個資料夾？
