### ISSUE TITLE
怎么配置rss

### ISSUE THREAD

**Issue by zhuyingshenshen** [D-Sketon/hexo-theme-reimu#59]
![3e34cb25-bec7-4981-b535-c68a02a0e1d6](https://github.com/user-attachments/assets/99a8d462-a105-488d-895f-ac7e89fd9cb8)
![4d572c83-2818-4b55-9518-fb23e4a128d2](https://github.com/user-attachments/assets/6a3bb973-2671-4f55-a872-3e45437c5ffe)
![35511f8c-3b96-4e70-9e91-4f10ae293031](https://github.com/user-attachments/assets/c653fa79-906b-4cd0-8917-9cf5c24dee86)
这样不行

**Comment by D-Sketon** [comment]
不清楚你想要怎样的RSS
reimu主题仅仅提供指向生成的RSS的超链接按钮，RSS配置细节还是需要查看[hexo-generator-feed](https://github.com/hexojs/hexo-generator-feed)的readme
