### ISSUE TITLE
markdown链接前缀如何修改

### ISSUE THREAD

**Issue by ShqWW** [D-Sketon/hexo-theme-reimu#62]
‘#’ 前缀不好看 想换成其它图标或标识 在哪里修改
![image](https://github.com/user-attachments/assets/fdb7d7f2-db9e-409c-9247-5d39950f4222)

**Comment by D-Sketon** [comment]
https://github.com/D-Sketon/hexo-theme-reimu/blob/main/source%2Fjs%2Fpjax_script.js#L30-L40

**Comment by ShqWW** [comment]
感谢回复，另外请问一下如果想修改默认字体如何修改，比如把默认的宋体改成微软雅黑

**Comment by ShqWW** [comment]
问题已解决
