### ISSUE TITLE
同时兼容 KaTeX 和 MathJax

### ISSUE THREAD

**Issue by ShqWW** [D-Sketon/hexo-theme-reimu#63]
问题示例：
```
$$
\begin{align}
&\underset{\boldsymbol{w}}{\min}\sum_{i=1}^N{\left( \boldsymbol{p}_i\boldsymbol{w} \right) ^2 },\,\, s.t. \,\left\| \boldsymbol{w} \right\| _2=1 \notag
\\
\Rightarrow &\underset{\boldsymbol{w}}{\min}\,\,\boldsymbol{w}^T\boldsymbol{P}^T\boldsymbol{Pw},\,\, s.t.\, \boldsymbol{w}^T\boldsymbol{w}=1
\end{align}
$$


```
临时解决方案：
https://shqww.github.io/2024/11/28/reimu%E5%8D%9A%E5%AE%A2%E4%BF%AE%E6%94%B9/

有什么其他好的解决方案

**Comment by D-Sketon** [comment]
将 `hexo-renderer-markdown-it-plus` 替换为 `@reimujs/hexo-renderer-markdown-it-plus` 试试

**Comment by D-Sketon** [comment]
pin: 
https://github.com/KaTeX/KaTeX/issues/3066
https://github.com/KaTeX/KaTeX/issues/3254
以上问题待修复

**Comment by D-Sketon** [comment]
以上问题已于 91ef8ad 修复
效果请看：https://d-sketon.github.io/20240114/hexo-theme-reimu-content/#%E6%95%B0%E5%AD%A6%E5%85%AC%E5%BC%8F

**Comment by ShqWW** [comment]
问题仍然存在
![image](https://github.com/user-attachments/assets/dd590862-c239-4d4e-8b07-ae9d0193c02f)

**Comment by D-Sketon** [comment]
`npm ls --depth=2` 查看一下 @vscode/markdown-it-katex 是否依赖的最新的katex
```
+-- @reimujs/hexo-renderer-markdown-it-plus@1.0.0
| +-- @vscode/markdown-it-katex@1.1.0
| | `-- katex@0.16.11
```

**Comment by ShqWW** [comment]
这是我的结果
![image](https://github.com/user-attachments/assets/a2c4ba14-2864-47f7-9d0f-3d3202d97807)
`themes/reimu/layout/_partial/head.ejs` 里的math和博客markdown文件里的math变量都设置为true了

**Comment by D-Sketon** [comment]
我尝试创建了一个新博客 [D-Sketon/reimu-playground-katex](https://github.com/D-Sketon/reimu-playground-katex)，但是仍然无法复现= =

**Comment by D-Sketon** [comment]
我给katex加个配置吧，允许走客户端渲染

**Comment by ShqWW** [comment]
我新建一个hexo项目还是一样的问题：

复现步骤：
0.新建项目
```
hexo init myhexo
cd myhexo
```
1. 替换插件
---
npm uninstall hexo-renderer-marked --save
npm install @reimujs/hexo-renderer-markdown-it-plus --save
---
2.更换主题
```
git clone https://github.com/D-Sketon/hexo-theme-reimu.git themes/reimu
```
3. _config.yaml 121 行， 
```
# need https://github.com/webappdevelp/hexo-filter-mermaid-diagrams
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: false
```
4. hello-world.md 的开头
---
---
title: Hello World
math: true
---
---

**Comment by ShqWW** [comment]
好像可以正常渲染了 我再试试其它测试用例

**Comment by ShqWW** [comment]
目前公式渲染没问题了，但是编号引用仍然有问题
```
$$
\begin{align}
d_i=\frac{a\hat{x}_i+b\hat{y}_i}{\sqrt{a^2+b^2}} \label{distance}
\end{align}
$$
```
![image](https://github.com/user-attachments/assets/b050da2d-a0f3-4a9e-863c-3b251d9f1a28)

**Comment by D-Sketon** [comment]
https://github.com/KaTeX/KaTeX/issues/2003 这是katex的问题了。。

**Comment by ShqWW** [comment]
可否考虑添加mathjax和katex两种插件自由选择

**Comment by D-Sketon** [comment]
3d8a6f0 和 d31e83c 实现了katex客户端渲染和mathjax3支持

**Comment by ShqWW** [comment]
'''
$$
\begin{align}
\sum_{i=1}^N{d_{i}^{2}}&=\boldsymbol{w}^T\boldsymbol{P}^T\boldsymbol{Pw}\notag
\\
&=\left( -\lambda \right) \boldsymbol{w}^T\left( -\lambda \right) \boldsymbol{w}\notag
\\
&=\lambda ^2\boldsymbol{w}^T\boldsymbol{w}=\lambda^2
\end{align}
$$
'''

![image](https://github.com/user-attachments/assets/17aef5fb-32d5-40b2-a74a-c6fd2d4dc22d)
![image](https://github.com/user-attachments/assets/bf109a60-ea9d-4298-af13-3c46ce49d3e3)

 切换mathjax3 公式渲染出现多余字符串和不对齐等问题， katex没有问题

**Comment by D-Sketon** [comment]
要把渲染器改回 `hexo-renderer-marked` ，katex和mathjax3不能共存

**Comment by D-Sketon** [comment]
我这里切回去后好像没什么问题 https://d-sketon.github.io/reimu-playground-katex/2024/11/30/hello-world/

**Comment by D-Sketon** [comment]
目前看来要保证换行的话得把latex包在raw语句中才能生效
```yml
{% raw %}
$$
\begin{align}
&\underset{\boldsymbol{w}}{\min}\sum_{i=1}^N{\left( \boldsymbol{p}_i\boldsymbol{w} \right) ^2 },\,\, s.t. \,\left\| \boldsymbol{w} \right\| _2=1 \notag
\\
\Rightarrow &\underset{\boldsymbol{w}}{\min}\,\,\boldsymbol{w}^T\boldsymbol{P}^T\boldsymbol{Pw},\,\, s.t.\, \boldsymbol{w}^T\boldsymbol{w}=1
\end{align}
$$
{% endraw %}
```
![{4F60B543-72D1-42EE-83C3-2F2C57766B22}](https://github.com/user-attachments/assets/6fd6dc94-4574-4b88-b288-3f0a44863981)

**Comment by ShqWW** [comment]
那暂时使用katex吧
