### ISSUE TITLE
能否默认折叠部分代码块

### ISSUE THREAD

**Issue by syhanjin** [D-Sketon/hexo-theme-reimu#66]
我需要在 post 内附上一些完整的代码文件，这样 post 就会非常长，同时严重影响性能（未折叠代码块时能感觉到明显的页面滑动卡顿），我想如果能默认折叠这些代码块能够给读者带来更好的体验。
也不知道好不好实现。

**Comment by D-Sketon** [comment]
考虑在v1.1.0里加个配置

**Comment by D-Sketon** [comment]
v1.1.0 已发布
添加了配置用于控制代码块的默认展开状态，`expand` 可以设置为 `true`、`false` 或数字，数字表示当代码块的行数大于该数字时默认收缩。
  ```yaml
  code_block:
    expand: true # true | false | number
  ```
