### ISSUE TITLE
为什么更新不成功

### ISSUE THREAD

**Issue by zhuyingshenshen** [D-Sketon/hexo-theme-reimu#67]
![image](https://github.com/user-attachments/assets/0b92311e-001d-4a36-b57b-a13e3e574fc6)

为什么更新不了1.0.0

**Comment by D-Sketon** [comment]
npm update 应该是不会更新major版本的升级的

**Comment by zhuyingshenshen** [comment]
那应该怎么更新

**Comment by zhuyingshenshen** [comment]
npm install hexo-theme-reimu --save也不行

**Comment by D-Sketon** [comment]
npm install hexo-theme-reimu@1 试试

**Comment by zhuyingshenshen** [comment]
> npm install hexo-theme-reimu@1 试试

ok了谢谢了
