### ISSUE TITLE
部署到服务器上，报错GET https://npm.webcache.cn/photoswipe@5.4.4/dist/photoswipe-lightbox.esm.min.js 403 (Forbidden)

### ISSUE THREAD

**Issue by yys204** [D-Sketon/hexo-theme-reimu#69]
![image](https://github.com/user-attachments/assets/d0791aa2-e5c0-4473-94ed-0b65db9e8a18)
大佬，你好，我打包后部署到自己服务器上，报这个错，导致图片获取不了，这是为什么，本地node环境下启动，不会这样。

**Comment by D-Sketon** [comment]
有博客网址链接吗，我看一下

**Comment by yys204** [comment]
> 有博客网址链接吗，我看一下

http://114.132.45.7/

**Comment by D-Sketon** [comment]
看了一下，webcahce这个cdn是直接禁止公网ip访问的
建议参考 https://github.com/D-Sketon/hexo-theme-reimu?tab=readme-ov-file#vendor 把cdn改成jsdelivr

**Comment by D-Sketon** [comment]
像这样
```patch
 js:
     photoswipe:
-      src: webcache|photoswipe@5.4.4/dist/photoswipe.esm.min.js
+      cdn_jsdelivr_npm: webcache|photoswipe@5.4.4/dist/photoswipe.esm.min.js
      integrity: sha384-WkkO3GCmgkC3VQWpaV8DqhKJqpzpF9JoByxDmnV8+oTJ7m3DfYEWX1fu1scuS4+s
```

**Comment by yys204** [comment]
> 像这样
> 
> ```diff
>  js:
>      photoswipe:
> -      src: webcache|photoswipe@5.4.4/dist/photoswipe.esm.min.js
> +      src: cdn_jsdelivr_npm|photoswipe@5.4.4/dist/photoswipe.esm.min.js
>       integrity: sha384-WkkO3GCmgkC3VQWpaV8DqhKJqpzpF9JoByxDmnV8+oTJ7m3DfYEWX1fu1scuS4+s
> ```

感谢大佬解惑，已解决
