### ISSUE TITLE
感谢大佬，请问下文章数是怎么生成的？

### ISSUE THREAD

**Issue by stay-leave** [D-Sketon/hexo-theme-reimu#70]
https://stay-leave.github.io/
这是我刚部署的网站，但是我发现文章数是7，我看网页源码，里面就直接写了个7

怎么才能自动正确计数呢？在哪修改？
谢谢大佬

<img width="328" alt="image" src="https://github.com/user-attachments/assets/2a3a2bf2-a419-436c-8dc2-8705ed5f0891">

**Comment by qllokirin** [comment]
我看我的显示是正常的，你或许可以试试
hexo clean清除之前的
hexo g重新生成一下？

**Comment by D-Sketon** [comment]
这个文章计数是直接调用hexo内部的api获得的

**Comment by stay-leave** [comment]
抱歉啊，请问这个hexo 命令在哪执行？
我在网站文件夹下执行显示找不到命令，在大佬的主题文件夹下也是找不到命令
<img width="213" alt="image" src="https://github.com/user-attachments/assets/f73f946c-2e4c-43c1-a936-615b2e80c987">

**Comment by D-Sketon** [comment]
。？你是用 hexo 建站的吗
正常使用 hexo init 创建完博客文件夹后在里面是能直接使用 hexo 相关命令的

**Comment by stay-leave** [comment]
啊，我用的hugo
<img width="369" alt="image" src="https://github.com/user-attachments/assets/178035a3-7392-48dc-a818-de1179d9e7b5">

**Comment by D-Sketon** [comment]
如果你指的hugo-them-reimu的话，那个文章是包括了关于、友链、归档的页面的

**Comment by stay-leave** [comment]
https://themes.gohugo.io/themes/hugo-theme-reimu/
我在这里找到您的项目的。
好的，谢谢大佬解惑

**Comment by D-Sketon** [comment]
之后可能会修正这个统计方式
