### ISSUE TITLE
请问点击markdown的图片之后退出图片预览导致图片消失是什么原因

### ISSUE THREAD

**Issue by crimson000000** [D-Sketon/hexo-theme-reimu#9]
实例：

![](https://gitcode.net/crimson000000/mypic/-/raw/master/study/issue1.png)

![](https://gitcode.net/crimson000000/mypic/-/raw/master/study/issue2.png)

![](https://gitcode.net/crimson000000/mypic/-/raw/master/study/issue3.png)

**Comment by bingxin-ly** [comment]
难道是OIer？@crimson000000

**Comment by D-Sketon** [comment]
v0.0.7 修复了该bug
